"""DFT input generation and job management.

Generates GPAW and Quantum ESPRESSO input files from CIF structures
and manages local DFT calculations on macOS.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from pymatgen.core import Structure

logger = logging.getLogger(__name__)


def generate_gpaw_script(
    structure: Structure,
    output_dir: Path,
    job_name: str = "crystalmancer",
    xc: str = "PBE",
    kpoint_density: float = 3.0,
    encut: float = 500.0,
    smearing: float = 0.1,
) -> Path:
    """Generate a GPAW Python script for single-point DFT calculation.

    GPAW runs natively on macOS via pip install — no compilation needed.

    Parameters
    ----------
    structure : Structure
        pymatgen Structure to calculate.
    output_dir : Path
        Directory to write the GPAW script and CIF.
    job_name : str
        Name prefix for output files.
    xc : str
        Exchange-correlation functional (PBE, RPBE, etc.).
    kpoint_density : float
        k-point density parameter.
    encut : float
        Plane-wave energy cutoff (eV).
    smearing : float
        Fermi-Dirac smearing width (eV).

    Returns
    -------
    Path
        Path to the generated GPAW Python script.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save CIF
    cif_path = output_dir / f"{job_name}.cif"
    structure.to(str(cif_path), fmt="cif")

    # Calculate k-points from density
    lengths = [structure.lattice.a, structure.lattice.b, structure.lattice.c]
    kpoints = tuple(max(1, int(round(kpoint_density / l * 10))) for l in lengths)

    script = f'''#!/usr/bin/env python3
"""GPAW DFT calculation — auto-generated by Crystal Mancer."""

from ase.io import read, write
from gpaw import GPAW, PW, FermiDirac

# Load structure
atoms = read("{cif_path.name}")

# Set up calculator
calc = GPAW(
    mode=PW({encut}),
    xc="{xc}",
    kpts={kpoints},
    occupations=FermiDirac({smearing}),
    txt="{job_name}_gpaw.log",
    parallel={{"band": 1}},
)

atoms.calc = calc

# Single-point calculation
energy = atoms.get_potential_energy()
forces = atoms.get_forces()
stress = atoms.get_stress()

# Save results
import json
import numpy as np

results = {{
    "energy_eV": float(energy),
    "energy_per_atom_eV": float(energy / len(atoms)),
    "forces_eV_A": forces.tolist(),
    "max_force_eV_A": float(np.max(np.linalg.norm(forces, axis=1))),
    "stress_eV_A3": stress.tolist(),
    "num_atoms": len(atoms),
    "formula": atoms.get_chemical_formula(),
    "xc": "{xc}",
    "kpoints": list({kpoints}),
    "encut_eV": {encut},
}}

with open("{job_name}_results.json", "w") as f:
    json.dump(results, f, indent=2)

print(f"Energy: {{energy:.4f}} eV ({{energy/len(atoms):.4f}} eV/atom)")
print(f"Max force: {{np.max(np.linalg.norm(forces, axis=1)):.4f}} eV/Å")
'''

    script_path = output_dir / f"{job_name}_gpaw.py"
    script_path.write_text(script, encoding="utf-8")
    logger.info("Generated GPAW script: %s", script_path)
    return script_path


def generate_qe_input(
    structure: Structure,
    output_dir: Path,
    job_name: str = "crystalmancer",
    xc: str = "pbe",
    ecutwfc: float = 60.0,
    ecutrho: float = 480.0,
    kpoint_density: float = 3.0,
) -> Path:
    """Generate a Quantum ESPRESSO pw.x input file.

    Parameters
    ----------
    structure : Structure
        pymatgen Structure to calculate.
    output_dir : Path
        Directory for output files.

    Returns
    -------
    Path
        Path to the generated QE input file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    lattice = structure.lattice
    lengths = [lattice.a, lattice.b, lattice.c]
    kpoints = tuple(max(1, int(round(kpoint_density / l * 10))) for l in lengths)

    # Get unique elements
    elements = sorted(set(str(s.specie) for s in structure))

    # Build ATOMIC_SPECIES block
    species_lines = []
    for el in elements:
        pseudo = f"{el}.pbe-n-kjpaw_psl.1.0.0.UPF"
        from pymatgen.core import Element as PmgElement
        mass = PmgElement(el).atomic_mass
        species_lines.append(f"  {el}  {mass:.4f}  {pseudo}")

    # Build ATOMIC_POSITIONS block (crystal coordinates)
    pos_lines = []
    for site in structure:
        el = str(site.specie)
        fc = site.frac_coords
        pos_lines.append(f"  {el}  {fc[0]:.10f}  {fc[1]:.10f}  {fc[2]:.10f}")

    input_text = f"""&CONTROL
  calculation = 'scf',
  prefix = '{job_name}',
  outdir = './tmp/',
  pseudo_dir = './pseudo/',
  tprnfor = .true.,
  tstress = .true.,
/

&SYSTEM
  ibrav = 0,
  nat = {len(structure)},
  ntyp = {len(elements)},
  ecutwfc = {ecutwfc},
  ecutrho = {ecutrho},
  occupations = 'smearing',
  smearing = 'cold',
  degauss = 0.01,
/

&ELECTRONS
  conv_thr = 1.0d-8,
  mixing_beta = 0.3,
/

CELL_PARAMETERS angstrom
  {lattice.matrix[0][0]:.10f}  {lattice.matrix[0][1]:.10f}  {lattice.matrix[0][2]:.10f}
  {lattice.matrix[1][0]:.10f}  {lattice.matrix[1][1]:.10f}  {lattice.matrix[1][2]:.10f}
  {lattice.matrix[2][0]:.10f}  {lattice.matrix[2][1]:.10f}  {lattice.matrix[2][2]:.10f}

ATOMIC_SPECIES
{chr(10).join(species_lines)}

ATOMIC_POSITIONS crystal
{chr(10).join(pos_lines)}

K_POINTS automatic
  {kpoints[0]} {kpoints[1]} {kpoints[2]}  0 0 0
"""

    input_path = output_dir / f"{job_name}.pwi"
    input_path.write_text(input_text, encoding="utf-8")
    logger.info("Generated QE input: %s", input_path)
    return input_path


def parse_gpaw_results(results_path: Path) -> dict[str, Any] | None:
    """Parse GPAW JSON results file."""
    try:
        return json.loads(results_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, FileNotFoundError) as exc:
        logger.warning("Could not parse GPAW results: %s", exc)
        return None
